name: PublishToMaven

on:
  release:
    types: published
    branches: master

jobs:
  public-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        env:
          CI: true
        with:
          arguments: ":butterfly-android:uploadArchive -PossrhUsername=${{ secrets.OSSHR_USERNAME }} -PossrhPassword=${{ secrets.OSSHR_PASSWORD }} -PsigningPassword=${{ secrets.SIGNING_PASSWORD }} -PsigningKey=${{ secrets.SIGNING_KEY }}"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true